gui:
  mouseEvents: true
  theme:
    activeBorderColor:
      - '#ff0000'
      - bold
    inactiveBorderColor:
      - '#e600ff'
  nerdFontsVersion: "3"
  spinner:
    frames:
      - ''
      - ''
    rate: 500
git:
  parseEmoji: true
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --paging=never
  autoFetch: false
  autoRefresh: false
os:
  editPreset: "nvim"
